server:
  port: 3002

spring:
  application:
    name: auth-java-fe-client

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  host: localhost
  jwt:
    secret: my_secret

auth:
  server: http://localhost:8080
client:
  id: b-app

